const http=require('http');
const fs=require('fs');
const path=require('path');
const dns=require('dns').promises;
const {URL}=require('url');

const root=path.resolve(__dirname,'..');
const port=Number(process.env.PORT)||8787;
const blockedGroups=/adult|adulto|18\+|porn|sex/i;
const mimeTypes={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8'};

function parseAttributes(raw){const attrs={};const pattern=/([\w-]+)=(?:"([^"]*)"|'([^']*)'|([^\s]+))/g;let match;while((match=pattern.exec(raw)))attrs[match[1].toLowerCase()]=match[2]??match[3]??match[4]??'';return attrs;}
function parseM3U(text){const lines=text.replace(/^\uFEFF/,'').split(/\r?\n/).map(line=>line.trim()).filter(Boolean);const channels=[];for(let index=0;index<lines.length;index+=1){if(!lines[index].toUpperCase().startsWith('#EXTINF'))continue;const comma=lines[index].indexOf(',');const attrs=parseAttributes(comma>=0?lines[index].slice(0,comma):lines[index]);const name=(comma>=0?lines[index].slice(comma+1):attrs['tvg-name']||'Sem nome').trim()||'Sem nome';const category=(attrs['group-title']||'Outros').trim()||'Outros';let url='';for(let next=index+1;next<lines.length;next+=1){if(!lines[next].startsWith('#')){url=lines[next];index=next;break;}}if(!url||blockedGroups.test(category)||blockedGroups.test(name))continue;channels.push({id:`channel-${channels.length}-${Buffer.from(name+url).toString('base64').replace(/[^a-z0-9]/gi,'').slice(0,12)}`,name,logo:attrs['tvg-logo']||'',category,url});}return channels;}
function json(response,status,payload){const body=JSON.stringify(payload);response.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','Content-Length':Buffer.byteLength(body)});response.end(body);}
async function isPublicUrl(value){const target=new URL(value);if(!['http:','https:'].includes(target.protocol))return false;const records=await dns.lookup(target.hostname,{all:true});return records.every(record=>{const address=record.address;return !(/^(127\.|10\.|192\.168\.|169\.254\.)/.test(address)||address==='0.0.0.0'||address==='::1'||address.startsWith('fc')||address.startsWith('fe80:'));});}
async function readBody(request){let body='';for await(const chunk of request){body+=chunk;if(body.length>16384)throw new Error('Pedido demasiado grande.');}return JSON.parse(body||'{}');}
async function handlePlaylist(request,response){try{const {url}=await readBody(request);if(typeof url!=='string'||!await isPublicUrl(url))return json(response,400,{error:'Indica um URL HTTP(S) público de uma playlist autorizada.'});const upstream=await fetch(url,{redirect:'error',signal:AbortSignal.timeout(20000)});if(!upstream.ok)throw new Error(`A origem respondeu com HTTP ${upstream.status}.`);const text=await upstream.text();if(text.length>30*1024*1024)throw new Error('A playlist excede o limite de 30 MB.');return json(response,200,{channels:parseM3U(text)});}catch(error){return json(response,400,{error:error.message||'Não foi possível ler a playlist.'});}}
function serveFile(request,response){const requestPath=decodeURIComponent(new URL(request.url,'http://localhost').pathname);const relative=requestPath==='/'?'index.html':requestPath.slice(1);const filePath=path.resolve(root,relative);if(!filePath.startsWith(root)||!fs.existsSync(filePath)||fs.statSync(filePath).isDirectory())return json(response,404,{error:'Não encontrado.'});response.writeHead(200,{'Content-Type':mimeTypes[path.extname(filePath)]||'application/octet-stream'});fs.createReadStream(filePath).pipe(response);}
const server=http.createServer(async(request,response)=>{if(request.method==='POST'&&request.url==='/api/playlist')return handlePlaylist(request,response);if(request.method==='GET')return serveFile(request,response);return json(response,405,{error:'Método não suportado.'});});
server.listen(port,'0.0.0.0',()=>console.log(`TV Hub disponível na rede em http://0.0.0.0:${port}`));
