const state={channels:[],favorites:new Set(JSON.parse(localStorage.getItem('tvhub-favorites')||'[]')),activeView:'inicio',activeChannel:null};
const $=selector=>document.querySelector(selector);
const els={modal:$('#playlistModal'),form:$('#playlistForm'),url:$('#playlistUrl'),file:$('#playlistFile'),error:$('#formError'),load:$('#loadButton'),toast:$('#toast'),video:$('#videoPlayer'),player:$('#playerOverlay'),message:$('#playerMessage'),loading:$('#playerLoading')};
function escapeHtml(value){return String(value||'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[char]));}
function initials(name){return (name||'TV').split(/\s+/).filter(Boolean).slice(0,2).map(word=>word[0]).join('').toUpperCase();}
function parseAttributes(raw){const attrs={};const pattern=/([\w-]+)=(?:"([^"]*)"|'([^']*)'|([^\s]+))/g;let match;while((match=pattern.exec(raw)))attrs[match[1].toLowerCase()]=match[2]??match[3]??match[4]??'';return attrs;}
function parseM3U(text){const lines=text.replace(/^\uFEFF/,'').split(/\r?\n/).map(line=>line.trim()).filter(Boolean);const channels=[];for(let index=0;index<lines.length;index+=1){if(!lines[index].toUpperCase().startsWith('#EXTINF'))continue;const comma=lines[index].indexOf(',');const metadata=comma>=0?lines[index].slice(0,comma):lines[index];const name=(comma>=0?lines[index].slice(comma+1):'Sem nome').trim()||'Sem nome';const attrs=parseAttributes(metadata);let url='';for(let next=index+1;next<lines.length;next+=1){if(!lines[next].startsWith('#')){url=lines[next];index=next;break;}}if(!url)continue;channels.push({id:`channel-${channels.length}-${btoa(unescape(encodeURIComponent(name+url))).replace(/[^a-z0-9]/gi,'').slice(0,12)}`,name,logo:attrs['tvg-logo']||'',category:attrs['group-title']||'Outros',url});}return channels;}
function saveFavorites(){localStorage.setItem('tvhub-favorites',JSON.stringify([...state.favorites]));}
function channelCard(channel){const favorite=state.favorites.has(channel.id);const logo=channel.logo?`<img class="channel-logo" src="${escapeHtml(channel.logo)}" alt="" loading="lazy" onerror="this.hidden=true;this.nextElementSibling.hidden=false"><span class="channel-fallback" hidden>${escapeHtml(initials(channel.name))}</span>`:`<span class="channel-fallback">${escapeHtml(initials(channel.name))}</span>`;return `<article class="channel-card" tabindex="0" data-channel-id="${escapeHtml(channel.id)}"><div class="channel-visual">${logo}<button class="favorite-button ${favorite?'is-favorite':''}" data-favorite-id="${escapeHtml(channel.id)}" aria-label="${favorite?'Remover dos favoritos':'Adicionar aos favoritos'}">${favorite?'♥':'♡'}</button></div><div class="channel-copy"><div class="channel-name" title="${escapeHtml(channel.name)}">${escapeHtml(channel.name)}</div><div class="channel-category">${escapeHtml(channel.category)}</div></div></article>`;}
function renderGrid(target,channels,empty){$(target).innerHTML=channels.map(channelCard).join('');$(empty).hidden=channels.length>0;}
function render(){const categories=[...new Set(state.channels.map(channel=>channel.category).filter(Boolean))].sort((a,b)=>a.localeCompare(b));$('#channelStat').textContent=state.channels.length;$('#favoriteStat').textContent=state.favorites.size;$('#categoryStat').textContent=categories.length;$('#favoriteCount').textContent=state.favorites.size;$('#playlistStatus').textContent=state.channels.length?`${state.channels.length} canais disponíveis`:'Nenhuma playlist';$('.status-dot').classList.toggle('ready',state.channels.length>0);renderGrid('#homeGrid',state.channels.slice(0,8),'#homeEmpty');renderGrid('#liveGrid',state.channels,'#liveEmpty');const favorites=state.channels.filter(channel=>state.favorites.has(channel.id));renderGrid('#favoritesGrid',favorites,'#favoritesEmpty');$('#liveResultCount').textContent=`${state.channels.length} ${state.channels.length===1?'canal':'canais'}`;$('#favoriteResultCount').textContent=`${favorites.length} ${favorites.length===1?'canal':'canais'}`;renderCategories(categories);renderChannelSidebar();renderSearch($('#searchInput').value||'');}
function renderCategories(categories){$('#categoryNav').hidden=!categories.length;$('#categoryLinks').innerHTML=categories.map(category=>`<a class="category-link" href="#categoria-${encodeURIComponent(category)}" data-category="${escapeHtml(category)}"><span class="nav-icon">·</span>${escapeHtml(category)}</a>`).join('');}
function renderChannelSidebar(){const sidebar=$('#channelSidebar');sidebar.hidden=!state.channels.length;$('#channelLinks').innerHTML=state.channels.map(channel=>{const logo=channel.logo?`<img src="${escapeHtml(channel.logo)}" alt="" loading="lazy" onerror="this.hidden=true;this.nextElementSibling.hidden=false">`:'';return `<button class="channel-link" type="button" data-sidebar-channel-id="${escapeHtml(channel.id)}">${logo}<span class="channel-link-fallback" ${channel.logo?'hidden':''}>${escapeHtml(initials(channel.name))}</span><span class="channel-link-name">${escapeHtml(channel.name)}</span></button>`;}).join('');}
function renderSearch(query){const clean=query.trim().toLocaleLowerCase();const matches=clean?state.channels.filter(channel=>`${channel.name} ${channel.category}`.toLocaleLowerCase().includes(clean)):[];renderGrid('#searchGrid',matches,'#searchEmpty');$('#searchResultCount').textContent=`${matches.length} ${matches.length===1?'resultado':'resultados'}`;if(clean)$('#searchEmpty').hidden=true;}
function showView(view){const allowed=['inicio','ao-vivo','favoritos','pesquisa'];state.activeView=allowed.includes(view)?view:'inicio';document.querySelectorAll('.view').forEach(item=>item.classList.toggle('active',item.dataset.view===state.activeView));document.querySelectorAll('.nav-link').forEach(item=>item.classList.toggle('active',item.dataset.nav===state.activeView));$('#pageTitle').textContent={inicio:'Início','ao-vivo':'TV ao vivo',favoritos:'Favoritos',pesquisa:'Pesquisa'}[state.activeView];if(state.activeView==='pesquisa')$('#largeSearchInput').focus();}
function openModal(){els.modal.hidden=false;setTimeout(()=>els.url.focus(),50);}function closeModal(){els.modal.hidden=true;els.error.textContent='';}
function notify(message){els.toast.textContent=message;els.toast.classList.add('show');setTimeout(()=>els.toast.classList.remove('show'),3000);}
async function loadPlaylist(event){event.preventDefault();const url=els.url.value.trim();const file=els.file.files[0];if(!url&&!file){els.error.textContent='Indica um URL ou escolhe um ficheiro M3U.';return;}els.error.textContent='';els.load.disabled=true;els.load.innerHTML='<span class="spinner"></span> A carregar...';try{const result=file&&!url?{channels:parseM3U(await file.text())}:await (async()=>{const response=await fetch('/api/playlist',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url})});const data=await response.json();if(!response.ok)throw new Error(data.error||`HTTP ${response.status}`);return data;})();if(!result.channels?.length)throw new Error('A playlist não contém canais reconhecíveis.');state.channels=result.channels;render();closeModal();showView('ao-vivo');notify(`${result.channels.length} canais carregados`);}catch(error){els.error.textContent=`Não foi possível carregar a playlist. ${error.message}`;}finally{els.load.disabled=false;els.load.innerHTML='<span>↓</span> Carregar playlist';}}
function toggleFavorite(id){const channel=state.channels.find(item=>item.id===id);if(!channel)return;if(state.favorites.has(id))state.favorites.delete(id);else state.favorites.add(id);saveFavorites();render();if(state.activeChannel?.id===id)updatePlayerFavorite();}
function openPlayer(channel){state.activeChannel=channel;$('#playerTitle').textContent=channel.name;$('#playerCategory').textContent=channel.category;$('#playerLogo').innerHTML=channel.logo?`<img class="channel-logo" src="${escapeHtml(channel.logo)}" alt="" onerror="this.hidden=true;this.nextElementSibling.hidden=false"><span hidden>${escapeHtml(initials(channel.name))}</span>`:escapeHtml(initials(channel.name));updatePlayerFavorite();els.player.hidden=false;els.message.hidden=true;els.loading.hidden=false;els.video.hidden=false;els.video.autoplay=true;els.video.preload='auto';els.video.src=channel.url;els.video.play().catch(()=>{els.loading.hidden=true;els.message.hidden=false;});els.video.addEventListener('canplay',()=>{els.loading.hidden=true;},{once:true});els.video.addEventListener('error',()=>{els.loading.hidden=true;els.message.hidden=false;},{once:true});}
function updatePlayerFavorite(){const favorite=state.activeChannel&&state.favorites.has(state.activeChannel.id);$('#playerFavorite').textContent=favorite?'♥ Favorito':'♡ Favorito';}
function closePlayer(){els.video.pause();els.video.removeAttribute('src');els.video.load();els.player.hidden=true;state.activeChannel=null;}
document.addEventListener('click',event=>{const nav=event.target.closest('[data-nav]');if(nav){event.preventDefault();showView(nav.dataset.nav);if(window.innerWidth<800)$('#mobileMenu').click();return;}const sidebarChannel=event.target.closest('[data-sidebar-channel-id]');if(sidebarChannel){const channel=state.channels.find(item=>item.id===sidebarChannel.dataset.sidebarChannelId);if(channel)openPlayer(channel);return;}const category=event.target.closest('[data-category]');if(category){event.preventDefault();const matches=state.channels.filter(channel=>channel.category===category.dataset.category);renderGrid('#liveGrid',matches,'#liveEmpty');showView('ao-vivo');return;}const favorite=event.target.closest('[data-favorite-id]');if(favorite){event.stopPropagation();toggleFavorite(favorite.dataset.favoriteId);return;}const card=event.target.closest('.channel-card');if(card){const channel=state.channels.find(item=>item.id===card.dataset.channelId);if(channel)openPlayer(channel);}});
document.addEventListener('keydown',event=>{if(event.key==='Escape'){if(!els.modal.hidden)closeModal();else if(!els.player.hidden)closePlayer();return;}if((event.key==='Enter'||event.key===' ')&&document.activeElement?.classList.contains('channel-card')){event.preventDefault();document.activeElement.click();}});
$('#openPlaylist').addEventListener('click',openModal);$('#openPlaylistEmpty').addEventListener('click',openModal);$('#openPlaylistLive').addEventListener('click',openModal);$('#openPlaylistTop').addEventListener('click',openModal);$('[data-close-modal]').addEventListener('click',closeModal);els.modal.addEventListener('click',event=>{if(event.target===els.modal)closeModal();});els.form.addEventListener('submit',loadPlaylist);$('#closePlayer').addEventListener('click',closePlayer);$('#playerFavorite').addEventListener('click',()=>{if(state.activeChannel)toggleFavorite(state.activeChannel.id);});$('#searchInput').addEventListener('input',event=>{renderSearch(event.target.value);if(event.target.value)showView('pesquisa');});$('#largeSearchInput').addEventListener('input',event=>{$('#searchInput').value=event.target.value;renderSearch(event.target.value);});$('#mobileMenu').addEventListener('click',()=>$('.sidebar').classList.toggle('open'));window.addEventListener('hashchange',()=>{const view=location.hash.slice(1);if(view.startsWith('categoria-'))return;showView(view||'inicio');});render();showView(location.hash.slice(1)||'inicio');
